- id: python-unittest
  name: "Python unittest"
  entry: scripts/python-unittest.sh
  files: ""
  language: "script"
  description: "Runs `python -m unittest`"
- id: python-pytest
  name: "Python pytest"
  entry: scripts/python-pytest.sh
  files: ""
  language: "script"
  description: "Runs `python -m pytest`"
